# === Video Output & GPU API ===
vo=gpu-next                    # newest and most powerful video output in MPV
gpu-api=opengl                 # use Vulkan for best performance on Wayland

# === Hardware Acceleration ===
hwdec=nvdec-copy               # use NVIDIA NVDEC for hardware decoding
                               # the '-copy' suffix avoids many common issues

# === Smooth Playback & Sync ===
# video-sync=display-resample    # sync video to display refresh rate

# === Optional: high quality scaling ===
scale=ewa_lanczossharp         # high-quality scaling algorithm
cscale=ewa_lanczossharp

 
window-maximized=yes
no-keepaspect-window
no-osd-bar

sub-font='Vazirmatn'
sub-font-size=40
#sub-font-size=60
sub-shadow-color="#000000"
sub-shadow-offset=1.5

sub-color='#FFFF00' #subtitle color in rgb
sub-border-size=1
sid=auto
slang=per

volume=60

ao=pulse

osc=no

[Idle]
profile-cond=p["idle-active"]
profile-restore=copy-equal
title=' '
keepaspect=no
background=none
